-- Member promo wallet + redemption ledger.
-- Safe to re-run (IF NOT EXISTS). Do not use MySQL AUTO_INCREMENT syntax.

ALTER TABLE promotions
  ADD COLUMN IF NOT EXISTS usage_limit_per_member INTEGER NULL,
  ADD COLUMN IF NOT EXISTS is_collectible BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS stackable BOOLEAN NOT NULL DEFAULT FALSE;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'promotions_usage_limit_per_member_check'
  ) THEN
    ALTER TABLE promotions
      ADD CONSTRAINT promotions_usage_limit_per_member_check
      CHECK (usage_limit_per_member IS NULL OR usage_limit_per_member >= 1);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS member_promotions (
  member_promotion_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(member_id) ON DELETE CASCADE,
  promotion_id INTEGER NOT NULL REFERENCES promotions(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'saved'
    CHECK (status IN ('saved', 'used', 'expired')),
  saved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  used_at TIMESTAMPTZ NULL,
  UNIQUE (member_id, promotion_id)
);

CREATE INDEX IF NOT EXISTS idx_member_promotions_member_status
  ON member_promotions (member_id, status);
CREATE INDEX IF NOT EXISTS idx_member_promotions_promotion
  ON member_promotions (promotion_id);

CREATE TABLE IF NOT EXISTS booking_promotions (
  booking_promotion_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promotion_id INTEGER NOT NULL REFERENCES promotions(id),
  member_id INTEGER NOT NULL REFERENCES members(member_id),
  member_promotion_id INTEGER NULL REFERENCES member_promotions(member_promotion_id),
  room_booking_id INTEGER NULL REFERENCES room_bookings(room_booking_id) ON DELETE CASCADE,
  boat_booking_id INTEGER NULL REFERENCES boat_bookings(boat_booking_id) ON DELETE CASCADE,
  discount_amount NUMERIC NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT booking_promotions_one_header_check
    CHECK ((room_booking_id IS NOT NULL) <> (boat_booking_id IS NOT NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS booking_promotions_room_promo_unique
  ON booking_promotions (room_booking_id, promotion_id)
  WHERE room_booking_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS booking_promotions_boat_promo_unique
  ON booking_promotions (boat_booking_id, promotion_id)
  WHERE boat_booking_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_booking_promotions_promotion ON booking_promotions (promotion_id);
CREATE INDEX IF NOT EXISTS idx_booking_promotions_member ON booking_promotions (member_id);
CREATE INDEX IF NOT EXISTS idx_booking_promotions_room ON booking_promotions (room_booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_promotions_boat ON booking_promotions (boat_booking_id);
